---
- name: rhel 9 hardening
  hosts: all
  gather_facts: true
  vars:
    lock_user_list: ''
    #changed_all_user: true
  
  roles:
    - role: rhel-system-roles.timesync
      vars:
        timesync_ntp_provider: chrony
        timesync_ntp_servers:
          - hostname: server 0.asia.pool.ntp.org
            iburst: yes
          - hostname: server 1.asia.pool.ntp.org
            iburst: yes
    - role: rhel9-hardening

  tasks:
    - name: "Discover interactive users"
      ansible.builtin.shell: "getent passwd | awk -F: '($3 >= 1000){print $1}'"
      register: users

    - name: print the interactive users
      ansible.builtin.debug:
        var: users.stdout_lines

    - name: Unset password expiration for root user
      ansible.builtin.shell: "chage --maxdays 99999 {{ item }}"
      changed_when: false
      loop: "{{ pass_exp_excluded_users }}"

    - name: "Force user to change password first login"
      ansible.builtin.shell: "chage -d0 {{ item }}"
      loop: "{{ users.stdout_lines }}"
      when:
        - item != "ansible"
        - item != "nobody"
        - changed_all_user|bool  == true|bool

    - name: "Multi User | Force user to change password first login"
      ansible.builtin.shell: "chage -d0 {{ item }}"
      loop: "{{ lock_user_list.split('\n') }}"
      when: lock_user_list != ''
