---
#- name: Disable command warnings
#  set_fact:
#    ANSIBLE_COMMAND_WARNINGS: False

- name: "5.4.1 | PATCH | Ensure custom authselect profile is used"
  block:
      - name: "5.4.1 | AUDIT | Ensure custom authselect profile is used | Gather profiles"
        shell: 'authselect current | grep "Profile ID: custom/"'
        failed_when: false
        changed_when: false
        check_mode: no
        register: rhel9cis_5_4_1_profiles

      - name: "5.4.1 | AUDIT | Ensure custom authselect profile is used | Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ rhel9cis_5_4_1_profiles.stdout_lines }}"

      - name: "5.4.1 | AUDIT | Ensure custom authselect profile is used | Check if custom profile exists | Updated 2024"
        ansible.builtin.stat:
          path: "/etc/authselect/custom/{{ rhel9cis_authselect['custom_profile_name'] }}"
        register: custom_profile_exists

      - name: "5.4.1 | PATCH | Ensure custom authselect profile is used | Create custom profiles | Updated 2024 #remove warn:no parameter"
        shell: authselect create-profile {{ rhel9cis_authselect['custom_profile_name'] }} -b {{ rhel9cis_authselect['default_file_to_copy'] }}
        #args:
        #    warn: no
        register: rhel9cis_5_4_1_profiles_shell_output
        #failed_when: 
        when: rhel9cis_5_4_1_profiles.stdout == '' and not custom_profile_exists.stat.exists
      

- name: "5.4.2 | PATCH | Ensure authselect includes with-faillock"
  block:
      - name: "5.4.2 | AUDIT | Ensure authselect includes with-faillock | Gather profiles and enabled features"
        shell: "authselect current | grep with-faillock"
        failed_when: false
        changed_when: false
        check_mode: no
        register: rhel9cis_5_4_2_profiles_faillock

      - name: "5.4.2 | AUDIT | Ensure authselect includes with-faillock| Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ rhel9cis_5_4_2_profiles_faillock.stdout_lines }}"

      - name: "5.4.2 | PATCH | Ensure authselect includes with-faillock | Create custom profiles | Updated 2024 #remove warn:no parameter"
        shell: "authselect select custom/{{ rhel9cis_authselect['custom_profile_name'] }} with-faillock --force"
        #args:
        #    warn: no
        register: rhel9cis_5_4_2_profiles_shell_output
        when: "'- with-faillock' not in rhel9cis_5_4_2_profiles_faillock.stdout_lines"

- name: "5.5.2 | PATCH | Ensure system accounts are secured"
  lineinfile:
    path: /etc/security/faillock.conf
    state: present
    line: "{{ item }}"
  loop:
      - 'deny = {{ rhel9cis_pam_faillock.deny }}'
      - 'unlock_time = {{ rhel9cis_pam_faillock.unlock_time }}'
      - silent
  register: rhel9cis_5_5_2_profiles_shell_output

- name: "5.5.3 | PATCH | Ensure password reuse is limited | pwhistory"
  lineinfile:
    path: "/etc/authselect/custom/{{ rhel9cis_authselect['custom_profile_name'] }}/{{ item }}"
    state: present
    line: "password    requisite                                    pam_pwhistory.so remember={{ rhel9cis_pam_faillock.remember }} use_authtok"
    insertafter: '^password\s*requisite\s*pam_pwquality.so'
  loop:
    - system-auth
    - password-auth
  register: rhel9cis_5_5_3_profiles_shell_output

- name: "Save the current configuration"
  shell: authselect apply-changes
  when: (rhel9cis_5_4_1_profiles_shell_output.changed == true) or
        (rhel9cis_5_4_2_profiles_shell_output.changed == true) or
        (rhel9cis_5_5_2_profiles_shell_output.changed == true) or
        (rhel9cis_5_5_3_profiles_shell_output.changed == true)
